<?php
  $page = &atknew("atk.ui.atkpage");
  $ui =   &atknew("atk.ui.atkui");
?>

<HTML>
<HEAD>
<TITLE>menu</TITLE>
<link href="../../platform/atk/style.php" rel="stylesheet" type="text/css">
<LINK REL="stylesheet" HREF="<?php echo $ui->stylePath("dhtml_menu.css") ?>">
 
</HEAD>
<BODY background='<?php echo $g_layout->getImgSrc("dhtml_menu_bg.gif"); ?>'>
<script language="JavaScript" src="<?php echo $config_atkroot; ?>javascript/dhtml_menu_events.js" type="text/javascript">

</BODY>
</HTML>
